Adding std::min, std::max, std::sort to names.h
These are needed to fix compilation errors when min, max, 
and sort are used without specifying the namespace.

Change-Id: Ic960bdbb015e711486d8e7ad2149650ef342593d
Reviewed-on: http://gerrit.sjc.cloudera.com:8080/6548
Reviewed-by: David Alves <david.alves@cloudera.com>
Tested-by: Martin Grund <mgrund@cloudera.com>